Neos:
  GoogleAnalytics:
    sites:
      capitalclinic.com.au:
        analytics:
          id: 'UA-54876936-5'
        profileId: 203908607
        overrideHostname: 'capitalclinic.ambitlife.com.au'